name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 23

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm run test:unit

    - name: Start Vite server (wait for it to be ready)
      run: |
        npm run dev &
        # Wait for the Vite server to be ready by checking the health endpoint
        until curl -s http://localhost:3000; do
          echo "Waiting for Vite server to start..."
          sleep 5
        done
      env:
        CI: true

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test
